### ISSUE TITLE
非常感谢，编译可运行

### ISSUE THREAD

**Issue by daihao18** [issue-K/LOL-Cal-KDA#1]
不过发送到聊天框的记录可以做个优化，目前是json格式。

另外，有无计划做一个GUI

**Comment by issue-K** [comment]
你可以看看这里[link](https://github.com/real-web-world/hh-lol-prophet)

这是原作者,我这是复现的一个简单版本,gui的话他也做了,功能也多很多.

**Comment by issue-K** [comment]
> 不过发送到聊天框的记录可以做个优化，目前是json格式。
> 
> 另外，有无计划做一个GUI

你可以看看这里[link](https://github.com/real-web-world/hh-lol-prophet)

这是原作者,我这是复现的一个简单版本,gui的话他也做了,功能也多很多.

**Comment by daihao18** [comment]
阿里嘎多，非常感谢！
